name: First Workflow

on:
  - push

jobs: 
  first_job: 
    name: Devops first job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Execute Shell Script
        run: ./ascii-script.sh