name: First Workflow

on:
  - push

jobs: 
  first_job: 
    name: my updated job
    runs-on: ubuntu-latest
    steps:
        name: Checkout Code
        uses: actions/checkout@v6
        
      - name: Updated Welcome Message
        run: echo "Welcome to the CI/CD world with github actions"

      - name: List all Files including hidden files 
        run: ls -a

      - name: Display current working directory
        run: pwd